name: carl-bot
services:
  db:
    image: "mysql:8.4.0"
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    volumes:
      - /home/destroflyer/carl-bot/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 3s
      retries: 0
    restart: always
  db-ui:
    image: "destrostudios/phpmyadmin:latest"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "8091:443"
    restart: always
  app:
    build:
      dockerfile: app.Dockerfile
      args:
        DB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
        DISCORD_BOT_TOKEN: $DISCORD_BOT_TOKEN
        FLICKR_API_KEY: $FLICKR_API_KEY
        FLICKR_SHARED_SECRET: $FLICKR_SHARED_SECRET
        SPOTIFY_CLIENT_ID: $SPOTIFY_CLIENT_ID
        SPOTIFY_CLIENT_SECRET: $SPOTIFY_CLIENT_SECRET
    depends_on:
      db:
        condition: service_healthy
    restart: always